- group: internal network traffic
  enabled: false
  policy: exclude
  relation: and
  tags:
    - TE
  from-strings:
    - name: only network category
      def: kevt.category = 'net'

- group: rouge processes
  rules:
    - name: suspicious network {{ upper "activity" }}
      condition: kevt.category = 'net' and ps.name in ('at.exe', 'java.exe')
