- group: internal network traffic
  enabled: false
  tags:
    - TE
  rules:
    - name: only network category
      condition: kevt.category = 'net'
      min-engine-version: 2.0.0

- group: rouge processes
  rules:
    - name: suspicious network {{ upper "activity" }}
      condition: kevt.category = 'net' and ps.name in ('at.exe', 'java.exe')
      min-engine-version: 2.0.0
