name: rules

on:
  workflow_run:
    workflows: ["master", "pr"]
    types:
      - completed

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download MSI
      uses: dawidd6/action-download-artifact@v2
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: fibratus-amd64.msi
        path: .
        search_artifacts: true
    - name: Install Fibratus
      run: |
        $exec = Start-Process "msiexec" "/i fibratus-0.0.0-amd64.msi /qn /l*! install.log" -NoNewWindow -PassThru
        Start-Sleep -Seconds 2
        $tail = Start-Process "powershell" "Get-Content -Path install.log -Wait" -NoNewWindow -PassThru
        $exec.WaitForExit()
        $tail.Kill()
    - name: Validate rules
      run: |
        $env:Path += ";$env:ProgramFiles\Fibratus\Bin\"
        fibratus rules validate
