name: rules

on:
  workflow_run:
    workflows: ["master", "pr"]
    types:
      - completed

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download binary
      uses: dawidd6/action-download-artifact@v2
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: fibratus-amd64.exe
        path: .
        search_artifacts: true
    - name: Validate rules
      run: |
        ./fibratus.exe rules validate --filters.rules.from-paths=rules\* --filters.macros.from-paths=rules\macros\*
